# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# - task: DownloadSecureFile@1
#   name: SettingProfile
#   displayName: 'Downloading Profile for Databricks'
#   inputs:
#     secureFile: 'README.md'
# There was a resource authorization issue

- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '3.7.10'

- script: |
    sudo apt-get update
    sudo apt-get install libsasl2-dev
    sudo apt-get install git libpq-dev python-dev python3-pip 
    sudo apt-get remove python-cffi
    pip install --upgrade cffi
    pip install cryptography
  displayName: Install prerequisit Linux packages
  
  - script: |
    pip install dbt 
    pip install "dbt-spark[PyHive]" 
    export PATH=$PATH:/home/vsts_azpcontainer/.local/bin
    dbt compile
    dbt seed 
    dbt run
    dbt test
    dbt docs generate
  displayName: 'Compile, Test, and Run'